directories:
  output: release/${version}
  buildResources: build
appId: Markdown
copyright: Copyright © 2023 Ryanyan
productName: electron-test
asar: true
icon: public/vite.svg
files:
  - filter:
      - dist-electron
      - dist
mac:
  artifactName: ${productName}_${version}.${ext}
  target:
    - dmg
win:
  target:
    - target: nsis
      arch:
        - x64
  artifactName: ${productName}_${version}.${ext}
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
electronVersion: 27.1.2
